# Generated by Django 5.2.12 on 2026-03-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('agregado', 'Agregado / Ingreso'), ('vendido', 'Vendido / Apartado'), ('vencido', 'Vencido / Retirado')], default='agregado', max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='tejobar_app.producto')),
            ],
        ),
    ]
