# Generated by Django 5.2.12 on 2026-03-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0004_remove_partido_capitan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='precio_por_hora',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='pago_cancha',
            field=models.BooleanField(default=False),
        ),
    ]
