# Generated by Django 6.0.3 on 2026-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0005_cancha_precio_por_hora_partido_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora', 'cancha'), name='unique_cancha_horario'),
        ),
    ]
