# Generated by Django 6.0.3 on 2026-03-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0007_remove_partido_unique_cancha_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
