# Generated by Django 4.2.29 on 2026-03-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0013_alter_apartado_estado_alter_novedad_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='apartado',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apartado',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartados', to='tejobar_app.persona'),
        ),
    ]
