# Generated by Django 5.2.12 on 2026-03-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0003_partido_equipo1_partido_equipo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='capitan',
        ),
    ]
