# Generated by Django 6.0.3 on 2026-03-13 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0010_alter_jugadorequipo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='tejobar_app.producto'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo_novedad',
            field=models.CharField(choices=[('agregado', 'Agregado / Ingreso'), ('vendido', 'Vendido / Apartado'), ('vencido', 'Vencido / Retirado'), ('cancha', 'Pago de Cancha')], default='agregado', max_length=20),
        ),
    ]
