# Generated by Django 6.0.3 on 2026-03-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0011_alter_novedad_cantidad_alter_novedad_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='precio_por_hora',
            field=models.FloatField(default=8000.0),
        ),
    ]
