# Generated by Django 4.2.29 on 2026-03-26 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0012_alter_cancha_precio_por_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('comprado', 'Comprado'), ('cancelado', 'Cancelado / Abandonado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='tejobar_app.producto'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo_novedad',
            field=models.CharField(choices=[('agregado', 'Agregado / Ingreso'), ('vendido', 'Vendido / Apartado'), ('vencido', 'Vencido / Retirado'), ('cancha', 'Pago de Cancha'), ('perdida', 'Accidente / Pérdida')], default='agregado', max_length=20),
        ),
    ]
