# Generated by Django 4.2.29 on 2026-03-26 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0014_apartado_cliente_nombre_apartado_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El precio no puede ser 0 ni negativo.'), django.core.validators.MaxValueValidator(10000000.0, message='El precio excede el límite permitido (10M).')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo.'), django.core.validators.MaxValueValidator(10000, message='Capacidad máxima de bodega excedida (10,000 u).')]),
        ),
    ]
