# Generated by Django 4.2.29 on 2026-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0018_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='origen',
            field=models.CharField(blank=True, choices=[('COMPRA_PROVEEDOR', 'Compra a proveedor'), ('DEVOLUCION_CLIENTE', 'Devolución de cliente'), ('AJUSTE_INVENTARIO', 'Ajuste de inventario')], max_length=50, null=True),
        ),
    ]
