# Generated by Django 4.2.29 on 2026-06-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0024_cancha_descripcion_alter_cancha_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
