# Generated by Django 4.2.30 on 2026-06-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0026_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='pago_cancha_equipo1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partido',
            name='pago_cancha_equipo2',
            field=models.BooleanField(default=False),
        ),
    ]
