# Generated by Django 4.2.29 on 2026-06-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0028_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cancha_asociada',
            field=models.ForeignKey(blank=True, help_text='Deja vacío si este producto está disponible de forma general.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_asociados', to='tejobar_app.cancha', verbose_name='Cancha asociada (opcional)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='equipo_asociado',
            field=models.ForeignKey(blank=True, help_text='Asigna este producto a un equipo específico si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_asociados', to='tejobar_app.equipo', verbose_name='Equipo asociado (opcional)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='partido_asociado',
            field=models.ForeignKey(blank=True, help_text='Asigna este producto a un partido específico si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_asociados', to='tejobar_app.partido', verbose_name='Partido asociado (opcional)'),
        ),
    ]
