# Generated by Django 4.2.29 on 2026-06-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0029_producto_cancha_asociada_producto_equipo_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='tejobar_app.equipo'),
        ),
        migrations.AddField(
            model_name='apartado',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='tejobar_app.partido'),
        ),
    ]
