# Generated by Django 4.2.29 on 2026-06-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tejobar_app', '0030_apartado_equipo_apartado_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador_libre', models.CharField(blank=True, help_text='Nombre si el jugador es invitado o no está registrado', max_length=150, null=True)),
                ('tipo_novedad', models.CharField(choices=[('gol', '⚽ Gol'), ('amarilla', '🟨 Tarjeta Amarilla'), ('roja', '🟥 Tarjeta Roja'), ('lesion', '🤕 Lesión'), ('falta_asistencia', '❌ Falta de Asistencia'), ('otro', '📝 Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('minuto', models.PositiveSmallIntegerField(blank=True, help_text='Minuto del partido en que ocurrió (opcional)', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('jugador_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='tejobar_app.jugadorequipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_jugadores', to='tejobar_app.partido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad de Jugador',
                'verbose_name_plural': 'Novedades de Jugadores',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
