# Generated by Django 4.2.29 on 2026-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0031_novedadjugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedadjugador',
            name='minuto',
        ),
        migrations.AlterField(
            model_name='novedadjugador',
            name='tipo_novedad',
            field=models.CharField(choices=[('no_asistio', '❌ No asistió'), ('llego_tarde', '⏰ Llegó tarde'), ('lesion', '🤕 Se lastimó / Lesión'), ('sancionado', '🚫 Sancionado'), ('amonestado', '⚠️ Amonestado'), ('abandono', '🚪 Abandonó el partido'), ('otro', '📝 Otro')], max_length=30),
        ),
    ]
