# Generated by Django 4.2.29 on 2026-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0032_novedadjugador_remove_minuto_update_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'En Curso'), ('Cancelada', 'Cancelada'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
    ]
