# Generated by Django 4.2.29 on 2026-07-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0033_partido_estado_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='jugador_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_partido', to='tejobar_app.jugadorequipo'),
        ),
        migrations.AddField(
            model_name='apartado',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='HistorialSanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(blank=True, help_text='Nombre del jugador (si es invitado o no registrado)', max_length=150, null=True)),
                ('tipo_sancion', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sanciones', to='tejobar_app.partido')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones', to='tejobar_app.persona')),
            ],
            options={
                'verbose_name': 'Historial de Sanción',
                'verbose_name_plural': 'Historial de Sanciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PagoParcialJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_jugado_minutos', models.IntegerField()),
                ('tarifa_cancha_pagada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_consumos_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('jugador_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_parciales', to='tejobar_app.jugadorequipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_parciales', to='tejobar_app.partido')),
            ],
            options={
                'verbose_name': 'Pago Parcial de Jugador',
                'verbose_name_plural': 'Pagos Parciales de Jugadores',
                'unique_together': {('partido', 'jugador_equipo')},
            },
        ),
    ]
