# Generated by Django 4.2.29 on 2026-07-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0034_apartado_jugador_equipo_apartado_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadjugador',
            name='nombre_jugador_snapshot',
            field=models.CharField(blank=True, help_text='Nombre del jugador al momento de registrar la novedad (permanente)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='novedadjugador',
            name='jugador_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='tejobar_app.jugadorequipo'),
        ),
        migrations.CreateModel(
            name='PartidoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre capturado al inicio del partido', max_length=150)),
                ('nombre_equipo', models.CharField(blank=True, max_length=150, null=True)),
                ('es_capitan', models.BooleanField(default=False)),
                ('tipo_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrantes_snapshot', to='tejobar_app.equipo')),
                ('jugador_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_partido', to='tejobar_app.jugadorequipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes_snapshot', to='tejobar_app.partido')),
            ],
            options={
                'verbose_name': 'Integrante (Snapshot Partido)',
                'verbose_name_plural': 'Integrantes (Snapshot Partido)',
                'ordering': ['nombre_equipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='novedadjugador',
            name='partido_integrante',
            field=models.ForeignKey(blank=True, help_text='Referencia al snapshot histórico del jugador en este partido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='tejobar_app.partidointegrante'),
        ),
    ]
