# Generated by Django 4.2.29 on 2026-07-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0035_snapshot_integrantes_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialequipo',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='razon_salida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_equipos', to='tejobar_app.jugador'),
        ),
    ]
