# Generated by Django 6.0.3 on 2026-03-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0006_partido_unique_cancha_horario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partido',
            name='unique_cancha_horario',
        ),
        migrations.AddField(
            model_name='partido',
            name='hora_reserva_fin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
