# Generated by Django 4.2.30 on 2026-05-21 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0023_cancha_disponibilidad_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede superar los 200 caracteres.')], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='disponibilidad',
            field=models.CharField(error_messages={'blank': 'El nombre de la cancha es obligatorio.', 'null': 'El nombre de la cancha es obligatorio.', 'unique': 'Ya existe una cancha con este nombre.'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='El nombre de la cancha debe tener entre 2 y 50 caracteres.'), django.core.validators.MaxLengthValidator(50, message='El nombre de la cancha debe tener entre 2 y 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_por_hora',
            field=models.FloatField(default=8000.0, error_messages={'invalid': 'La tarifa por hora debe ser un valor numérico.'}, validators=[django.core.validators.MinValueValidator(0.01, message='La tarifa por hora debe ser mayor a 0.')]),
        ),
    ]
