# Generated by Django 5.2.12 on 2026-03-07 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0002_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='equipo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo1', to='tejobar_app.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo2', to='tejobar_app.equipo'),
        ),
    ]
