# Generated by Django 6.0.3 on 2026-03-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0009_producto_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugadorequipo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jugadorequipo',
            name='correo_invitado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jugadorequipo',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jugadorequipo',
            name='telefono_invitado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jugadorequipo',
            name='tipo_usuario',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('invitado', 'Invitado')], default='registrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='jugadorequipo',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_equipos', to='tejobar_app.jugador'),
        ),
    ]
