# Generated by Django 4.2.29 on 2026-05-19 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0019_movimientoinventario_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2, message='El nombre debe tener al menos 2 caracteres.'), django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]+$')]),
        ),
    ]
