# Generated by Django 4.2.29 on 2026-05-19 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0020_persona_nombre_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres.')]),
        ),
    ]
