# Generated by Django 4.2.29 on 2026-05-19 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejobar_app', '0021_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500, message='La descripción no puede superar los 500 caracteres.')], verbose_name='Descripción'),
        ),
    ]
